/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import styles from '@/styles/About.module.scss'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Foooter'

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.heading}>About</h1>
        <div className={styles.content}>
          <div className={styles.frame}>
            <img className={styles.img} src='/image.png' alt="Image" />
          </div>
          <div className={styles.para}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, ut labore et dolore magna aliqua. Sem et tortor consequat id porta. Semper eget duis at tellus at urna. Augue interdum velit euismod in pellentesque. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Cursus sit amet dictum sit amet justo. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Nullam vehicula ipsum a arcu cursus. Quam id leo in vitae turpis massa sed elementum tempus. Morbi leo urna molestie at elementum eu facilisis. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Neque gravida in fermentum et. Vehicula ipsum a arcu cursus vitae. A scelerisque purus semper eget. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Fames ac turpis egestas sed tempus urna.</p>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
